spring.application.name=app

# --- ACTIVE PROFILE: "dev" = H2  |  "prod" = Oracle ---
spring.profiles.active=prod

# --- JPA SHARED SETTINGS ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# --- UI & WEB SETTINGS ---
spring.thymeleaf.cache=false

# --- STATIC RESOURCES ---
spring.web.resources.static-locations=classpath:/static/
spring.web.resources.cache.period=3600
spring.servlet.mvc.hiddenmethod.filter.enabled=true

# --- LDAP CONFIGURATION ---
# Bayer Active Directory configuration for LDAP authentication
spring.ldap.urls=ldap://bayer.cnb:3268
spring.ldap.domain=ad-bayer-cnb\\
spring.ldap.authenticationmode=member
spring.ldap.base=OU=itaccounts,DC=bayer,DC=cnb
spring.ldap.filter=
spring.ldap.embedded.credential.username=MWYAI
spring.ldap.embedded.credential.password=Rcu8_3MwgRt=1mA

# --- LDAP TIMEOUT & CONNECTION SETTINGS ---
spring.ldap.timeout=5000
spring.ldap.read-timeout=5000
