# ==========================================
# PROD PROFILE — Oracle (Live / Online)
# ==========================================

# --- DATABASE CONNECTION ---
spring.datasource.url=jdbc:oracle:thin:@//bayeexa02np-oci-scan.bayer.cnb:1521/WCDEV.bayer.cnb
spring.datasource.driverClassName=oracle.jdbc.OracleDriver
spring.datasource.username=MZNZX
spring.datasource.password=Z3_s0u+9zAvpmBq

# --- JPA DIALECT ---
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
