# ==========================================
# DEV PROFILE — H2 (Offline / Local)
# ==========================================

# --- H2 CONSOLE ACCESS ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# --- DATABASE CONNECTION ---
spring.datasource.url=jdbc:h2:file:./data/appdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=USER,VALUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=12345678

# --- JPA DIALECT ---
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
